### ISSUE TITLE
Landing page UI bugs

### ISSUE THREAD

**Issue by custosDiretriz** [Custos-Diretriz/Custos-Dapp#1]
- Align existing animations With figma design and implement new animations from the figma design
- fix lunch custos dapp button to display the lunch dapp modal  instead of going to the services route
- fix button width and colours

**Comment by mercykolapo** [comment]
- [x] Give the header a heavier blur
![image](https://github.com/user-attachments/assets/e2ec7572-799b-4077-81cd-d59346340819)

- [x] Fix the star on the launch Custos Dapp button
![image](https://github.com/user-attachments/assets/8571b316-f4ea-4bf7-8cd3-ac5e0b19a9e4)

- [x] On hover, button changes to blue
![image](https://github.com/user-attachments/assets/1b65d09a-45d2-4ab2-87be-7bb055fbbe52)

- [x] The launch dapp button under agreement is opening a modal instead of redirecting to the agreement page. I think the button text should be changed to lcreate agreement and record video respectively.
![image](https://github.com/user-attachments/assets/8356cc80-655f-4cdf-9adf-7f7ee8c31298)
![image](https://github.com/user-attachments/assets/1dc32a76-b13d-4c8d-80f2-2178a152a5e0)
