### ISSUE TITLE
mobile view landing page bugs

### ISSUE THREAD

**Issue by custosDiretriz** [Custos-Diretriz/Custos-Dapp#17]
- [ ] make hamburger icon cover entire screen and eliminate modals for launch dapp and company rather listing them out according to the design https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=1633-3599&node-type=frame&t=J2dpVtjrrrc7mZQK-0
- [ ] align landing page texts and spacing to suit figma design https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=J2dpVtjrrrc7mZQK-0
- [ ] fix logo and hamburger spacing to look like the image below 
![image](https://github.com/user-attachments/assets/f3a86620-eec8-460c-8a56-c43ec67c2590)

**Comment by PoulavBhowmick03** [comment]
Gm! Is this issue for the ODHack? Or in general? I would love to get assigned and work on this!

### About me 
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

**Comment by Joshaw-k** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack web3 developer worked with various frontend frameworks over the years as well as different backend languages.

### How I plan on tackling this issue
Once I have understood the problem, I will fork the repo, and simulate the issue that was described. Depending on the complexity of the issue. If it is a frontend issue with an easy tag, I can raise a PR in minutes, but for more complex UI, I raise the PR the same day.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
hello @mercykolapo  i'm an experienced frontend developer and a blockchain developer i would love to work on this issue. Here is my onlydust profile [https://app.onlydust.com/u/martinvibes](https://app.onlydust.com/u/martinvibes)
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make sure to follow the instructions and apply the requested changes to pixel perfect 


### How I plan on tackling this issue
i would make sure it is very responsive accross all devices

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I am Sudipta Paul, and I have 1.5 years of experience in the field of blockchain development. I'm passionate about front-end development and UI/UX improvements, and I'm eager to contribute to improving the mobile view of this project.

### How I plan on tackling this issue
My approach: 

Modify the hamburger menu to expand and cover the entire mobile screen when clicked.
Ensure that the menu items ‘Launch Dapp’ and ‘Company’ are displayed directly in a list view, rather than using modals.
For the full screen changes could be made like this
 .hamburger-menu {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: #000;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
}  
Remove the modal functionality and display the items directly in a vertical list when the hamburger menu opens.

Compare the text alignment and spacing on the landing page with the Figma design.
Adjust the padding, margin, and text properties to ensure the alignment matches the Figma design. Like it could be made like this way

.landing-text {
  text-align: center;
  margin-top: 20px;
  line-height: 1.5;
}

Use of flexbox or grid to ensure proper alignment and spacing between the logo and the hamburger icon.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Fix hamburger icon to cover entire screen and remove modals for launch dapp and company
use the figma design to align landing page texts and spacing
Fix logo and hamburger spacing to look like the image above
ETA - 3 days

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To resolve the mobile view bugs on the landing page, I will implement several key changes to enhance usability and alignment with the Figma design.

First, I will adjust the hamburger icon to cover the entire screen. This modification will make it easier for users to access the menu, improving navigation throughout the app.

Next, I will eliminate the existing modals for launching the DApp and company information. Instead, I will organize these elements according to the design specifications outlined in the Figma link. This will streamline the user experience and maintain a cohesive layout.

 I will also ensure that all landing page texts and spacing are aligned correctly with the Figma design. This includes fine-tuning font sizes, margins, and padding to create a visually balanced and appealing presentation.

Finally, I will address the spacing between the logo and the hamburger icon to ensure it matches the provided reference image. This adjustment will contribute to a more polished and professional appearance.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:                                                               
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/



### How I plan on tackling this issue
To resolve the outlined issues, I propose the following professional action plan:

Enhance the Hamburger Icon Functionality: Redesign the hamburger icon to cover the entire screen when activated. This will provide users with an immersive navigation experience, facilitating easier access to menu options and streamlining the overall user interface.

Eliminate Modals for DApp Launch and Company Information: Remove the use of modals for presenting options related to launching the DApp and company details. Instead, prominently list these options directly on the landing page to ensure that users can easily access critical information without unnecessary interruptions.

Align Landing Page Texts and Spacing with Figma Design: Review and adjust all textual elements and their spacing on the landing page to ensure conformity with the specifications outlined in the Figma design. This will enhance visual coherence and readability, contributing to a polished and professional appearance.

Refine Logo and Hamburger Icon Spacing: Adjust the spacing between the logo and the hamburger icon to achieve a visually balanced header. This refinement will ensure that both elements are aligned with the design reference, creating a cohesive and inviting user interface.   

@Khauthymo I hope you give me the opportunity to contribute to this amazing project; I would be very grateful.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue, I’ll take the following the steps:

1.  I’ll use css to make the hamburger icon trigger a full-screen menu overlay (⁠ width: 100vw ⁠, ⁠ height: 100vh ⁠) and toggle its visibility with JavaScript.
2.⁠ ⁠I’ll then replace modal interactions for "Launch Dapp" and "Company" with simple navigation links, directly listed in the full-screen menu.
3.⁠ ⁠⁠Next, I’ll use exact values from the Figma design for typography and spacing, also adjusting with css properties and media queries for responsive design.
4.⁠ ⁠⁠I’ll also use css media queries to resize and reposition the cards, to ensure they display properly on smaller screens without overlapping or cramped layouts.
5.⁠ ⁠⁠Lastly, I’ll fix logo and hamburger spacing to look like the image provided.

Please assign me, I’m ready to work.

**Comment by ridwanalaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a frontend developer with 2 years experience building applications

### How I plan on tackling this issue
make hamburger icon cover entire screen and remove modals for launch dapp and company, align landing page texts and spacing to suit figma design and fix logo and hamburger spacing to look like the image above
ETA - 3 days

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Here's my approach to fixing these mobile landing page issues:

1. Hamburger Menu Overhaul:
   - I'll implement a full-screen overlay menu on hamburger click
   - Remove existing modals for launch dapp and company sections
   - Create a vertical list layout matching the Figma design
   - Add smooth transitions for menu open/close
   - Ensure proper z-indexing and backdrop handling

2. Text and Spacing Alignment:
   - Will implement a pixel-perfect match to the Figma specs:
     - Review and adjust all text margins and padding
     - Fix line heights and font weights
     - Ensure consistent spacing between sections
     - Match exact breakpoints from design
   - Use CSS custom properties for maintainable spacing values

3. Logo and Hamburger Positioning:
   - Implement proper spacing between logo and hamburger icon
   - Add exact padding values from design
   - Ensure header stays fixed during scroll
   - Test different screen sizes to maintain consistent spacing

Implementation Timeline:
- Day 1: Hamburger menu revamp
- Day 1-2: Text and spacing fixes
- Day 2: Logo/hamburger positioning

QA Process:
- Compare implementation against Figma specs using overlay tool
- Test on various mobile devices (iOS/Android)
- Verify smooth animations and transitions
- Check responsive behavior across breakpoints

Expected completion: 2 days

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a web2 and web3 developer and want to contribute to the open source and fix the issues raised.

### How I plan on tackling this issue
I would do as
1. hamburger icon, which should occupy the entire screen and dismiss modals.
2. Text Alignment: The spacings and texts of the landing page should be according to Figma design.
3. Logo and Hamburger Spacing: Use the fix spacing on logo and hamburger icon.

**Comment by Psalmuel01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a strong background in frontend engineering, UI/UX design, and Web3 development. Over the years, I’ve honed my skills in JavaScript frameworks like React and Next.js, as well as blockchain technologies. This gives me a unique edge in solving both technical and user experience problems.

I particularly have strong expertise in converting ui screes to accurate frontend, so this should be an easy one.

### How I plan on tackling this issue
To match the design from the Figma links, here’s how I’ll proceed:

1. Hamburger Icon Covering Entire Screen
   - I’ll modify the CSS and JavaScript to make the hamburger menu expand to full screen when clicked. This will likely involve using `position: fixed`, setting the width and height to `100%`, and ensuring the z-index is high enough to cover other elements on the page.
   - Instead of modals for “Launch Dapp” and “Company,” I’ll list them out directly within the expanded hamburger menu, following the design guidelines in Figma. This ensures better flow and consistency with the visual design.

2. Align Landing Page Texts and Spacing
   - I’ll carefully inspect the Figma design to replicate the text alignment and spacing exactly. This will involve fine-tuning the margins, padding, font sizes, and line heights to ensure they are pixel-perfect compared to the design.

This way, the UI will maintain the clean and professional look intended in the Figma files, ensuring consistency and user-friendly navigation.

**Comment by Goodness5** [comment]
@Joshaw-k still waiting for your update on this issue

**Comment by Joshaw-k** [comment]
> @Joshaw-k still waiting for your update on this issue

Done, please review
