### ISSUE TITLE
Crime recorder

### ISSUE THREAD

**Issue by custosDiretriz** [Custos-Diretriz/Custos-Dapp#18]
- [ ] Implement user friendly error handling and success messages components on every page
- [ ] modify modals to blur the overlaying page 
- [ ] the video/image cards on smaller screens looks weird
![Screenshot from 2024-10-18 10-58-25](https://github.com/user-attachments/assets/760ecb48-385c-4a6a-a11d-184812ca703e)

- [ ] camera remains active after taking pictures and routing to the video pages

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum ecosystem.

I would love to work on this, if available, be it now or in the ODHack!

### How I plan on tackling this issue
I can solve this issue by customising the CSS of the file
ETA - 1 day

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi @custosDiretriz @Goodness5 , I'd love to be assigned this issue please. This would be my first time contributing to this repo and I'd love to be given the opportunity.ould love to contribute to this project. :) I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue:
1.⁠ ⁠I’ll create reusable components for error and success messages, ensuring they are user-friendly and consistent across all pages. 
2.⁠ ⁠I’ll adjust the css for responsiveness(by using media queries to ensure video and image cards look good on smaller screens and also ensure to fix the cards padding/margins so that they don’t overlap or look distorted).
3.⁠ ⁠⁠Lastly, I’ll ensure the camera stops running after taking a picture and navigating away.

Please assign me. I am ready to work.

**Comment by Goodness5** [comment]
@PoulavBhowmick03 @od-hunter thanks for showing interest in this you can apply for the issue via the odhack 9 very soon thanks

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Implement user friendly success and error handling message components on every page
Add blur to the modals to blur the overlaying page
Fix image/video cards on smaller screens
ETA - 72hrs

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

### How I plan on tackling this issue
i would make sure it is very responsive accross all devices

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I propose implementing user-friendly error handling and success message components across all pages. These components will ensure that users receive clear feedback about their actions, helping them understand any issues that arise or confirming successful operations. The messages will be designed to be visually distinct and easily noticeable, contributing to a smoother user journey.

Additionally, I will modify the modals to blur the overlaying page. This visual effect will create a more immersive experience by emphasizing the modal content and reducing distractions from the background.

I will also address the layout issues with video and image cards on smaller screens, ensuring they display correctly and maintain a cohesive look. This involves adjusting the CSS and layout properties to ensure the cards are responsive and user-friendly.

Finally, I will resolve the issue of the camera remaining active after taking pictures. Once a photo is captured, I will implement a mechanism to automatically deactivate the camera and route users back to the video page, ensuring a seamless transition.

By implementing these improvements, the Crime Recorder application will provide a more intuitive and enjoyable user experience, encouraging users to engage with the app effectively.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:                                                               
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/



### How I plan on tackling this issue
Implement User-Friendly Error Handling and Success Messages:

I will create a reusable notification component that displays error and success messages on every page. This component will use context for global accessibility, allowing components to trigger notifications easily. It will also include automatic dismissal and different styling for errors and successes to improve user experience.
Modify Modals to Blur the Overlaying Page:

I will enhance the modal functionality by adding a CSS class that applies a blur effect to the background when the modal is open. This will involve modifying the modal's open and close logic to toggle the blur class on the body or main content container.
Fix the Layout of Video/Image Cards on Smaller Screens:

I will implement responsive design principles by using CSS media queries to ensure video/image cards adapt to various screen sizes. This will include adjusting widths, heights, and layout styles to maintain visual consistency and usability across devices.                                                                                                                                                          @Khauthymo I hope you give me the opportunity to contribute to this amazing project; I would be very grateful.

**Comment by bruhhgnik** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm nik
I'm a linux, blockchain and ML developer

### How I plan on tackling this issue
I will:

Fix error handling across all pages
Add modal backdrop blur effect
Improve video/image card responsiveness
Fix camera deactivation after capture

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello, can I be assigned to work on this issue?

I'm a software developer with over 4 years experience

Here's my OnlyDust profile https://app.onlydust.com/u/raizo07

ETA: One day

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Here's my approach to fixing the Crime Recorder issues:

Error/Success Message System:
I'll implement a global toast notification system:
This is a sample of what the notification props would look like 

type NotificationType = 'success' | 'error' | 'warning';
interface NotificationState {
  message: string;
  type: NotificationType;
  duration: number;}


Add context-specific error messages
Ensure messages are clear and actionable
Add proper animation for better UX

Modal Overlay Enhancement:
Implement backdrop blur effect:
Add smooth transitions
Ensure proper z-index handling
Lock body scroll when modal is open

Media Card Responsive Fixes:
Implement proper grid system for cards
Add dynamic sizing based on viewport
Fix aspect ratio issues
Optimize image/video thumbnails
Add proper loading states

Camera Resource Management:
Fix camera cleanup on route change:
This is a sample if what the cleanup implementation would look like
useEffect(() => {
  return () => {
    if (stream) {
      stream.getTracks().forEach(track => track.stop());
    }
  };
}, [stream]);


Add proper error handling for camera access
Implement loading states during camera init
Add camera permission checks

Expected Timeline: 3-4 days

**Comment by faytey** [comment]
@Ayoazeez26 are you still working on this
