### ISSUE TITLE
Crime recorder UI fixes

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/Custos-Dapp#22]
- [ ] Fix record button and switch camera button
- [ ] Animate switch camera button
- [ ] Start and stop recording buttons should have active state
- [ ] Fix body scroll into footer 
<img width="1182" alt="Screenshot 2024-10-23 at 09 44 10" src="https://github.com/user-attachments/assets/0b6f0879-81ef-4af6-bbaa-99f98a9270c7">

**Comment by martinvibes** [comment]
Hello @Khauthymo I'm a frontend developer and a blockchain dev I would like to work on this issue :)

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I’m Sudipta Paul, a full-stack developer with 1.5 years of experience in blockchain and web development. I would like to help with the Crime Recorder UI fixes, particularly for the buttons and footer behavior.

### How I plan on tackling this issue
Approach to resolve this issue

I will inspect the current state of these buttons and update their styles and positioning as needed. i will ensure they are fully functional and intuitive on both desktop and mobile views.
Animate Switch Camera Button:

I will add smooth cssanimations for the switch camera button, such as a rotate or slide effect, to indicate action clearly when switching between cameras.

I will add visual feedback for the start and stop recording buttons by implementing active states. This will include color changes or shadow effects to indicate when the button is clicked and recording is in progress.

To prevent the body from scrolling into the footer, i will inspect the overflow settings and apply necessary changes such as limiting the scrollable content or adjusting the layout. This ensures the footer remains fixed at the bottom while the rest of the content scrolls appropriately.

Will test the Ui for responsiveness, ensuring the buttons are functional and visually appealing on various screen sizes, and that the footer behaves as expected on all devices.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Check the current state of the record button and the switch camera button
Check out and implement animation for the switch camera button
Create and implement an active state for start and stop recording buttons
Fix body scroll into the footer
ETA - 3 days

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
 need to make the following fixes: 

  

1. I’ll fix the record button and the switch camera button. 

2. I’ll add an animation to the switch camera button. 

3. I’ll ensure the start and stop recording buttons have an active state. 

4. I’ll fix the body scroll issue that’s affecting the footer.

**Comment by melnikga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, my name is Georgiy, I'm a frontend developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

### How I plan on tackling this issue
I would implement proper active states for the record control buttons and add a smooth animation for the camera switch button. I would also fix the body scroll issue that's currently affecting the footer area. For styling, I would use Tailwind's animation utilities and make sure all interactive elements have clear visual feedback states.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this am
azing project.

Some frontend projects that i have:                                                               
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/


### How I plan on tackling this issue
1. **Fix Buttons**: Ensure the record and switch camera buttons trigger the correct functions and handle errors.

2. **Animate Switch Camera Button**: Use CSS, TailwindCSS to animate the switch camera button.

3. **Active State for Recording Buttons**: Add a class to indicate the active state for start and stop recording buttons.

4. **Fix Body Scroll**: Use CSS, TailwindCSS  to prevent the body from scrolling into the footer during recording.

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue:
1.⁠ ⁠I’ll fix functionality for the record and switch camera buttons by implementing appropriate event handlers.
2.⁠ ⁠I’ll use css transitions to enhance user experience.
3.⁠ ⁠I’ll implement active states for the recording button using conditional class application based on the recording state.
4.⁠ ⁠I’ll adjust body and footer css to ensure the body does not scroll into the footer, providing proper spacing and overflow control.

Please assign me, I’m ready to work.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm  a web2 and web3 developer and want to work on the issues raised :)

### How I plan on tackling this issue
I will proceed as
1. Repair the record button and camera switch button.
2. Add a little animation to the camera switch button to enhance interactivity.
3. Ensure that the record start and stop buttons become active upon click. 
4. Position the body scroll so that the footer does not cover underneath.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
i am a python dev and want to work on this
