### ISSUE TITLE
Agreement UI fixes

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/Custos-Dapp#23]
- [ ] Sign agreement modal should display an image instead of the ID number
- [ ] Fix mobile responsiveness on edit agreement headers
- [ ] On edit agreement page, connect validate/sign agreement button to validate/sign agreement modals

**Comment by MayowaObisesan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a web3 frontend developer with full-stack development experience.
I have worked on various frontend projects building exciting and captivating UI for good User Experience. I believe in pixel-perfect design and UI implementations.
I have a knack for building amazing web and mobile UI.

### How I plan on tackling this issue
Once I have understood the problem, I will fork the repo and simulate the issue that was described. Depending on the complexity of the issue. If it is a frontend issue with an easy tag, I can raise a PR in minutes, but for more complex UI, I raise the PR the same day.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello @Khauthymo I'm a frontend developer  and would like to work on this issue :)

### How I plan on tackling this issue
i would make sure it is working and responsive accross all devices

**Comment by jedstroke** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a seasoned fullstack web3 developer with a knack for crafting pixel-perfect UI designs.  Here's my lil' portfolio: https://www.jedshock.com

### How I plan on tackling this issue
I will ensure the existing UI adheres to good UX principles, focusing on key elements such as consistency, accessibility, and intuitive design. Consistency will be maintained throughout the interface by using uniform elements, layouts, and behaviors across all screens, ensuring a cohesive user experience. Accessibility will be prioritized by following standards that accommodate diverse users, including those with disabilities, by implementing features like proper color contrast, screen reader compatibility, and keyboard navigation. Additionally, I'll ensure the UI is intuitive, allowing users to easily navigate and interact with the app without confusion, creating a seamless and enjoyable experience.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will ensure that all the criteria on the description are met by displaying an image in the sign agreement modal instead of an id number, fixing responsiveness and connecting validate sign buttons 2-3 days

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, I’m Sudipta Paul, a full-stack developer with 1.5 years of experience in blockchain and web development. I’d like to help resolve the uifixes for the Agreement section.


### How I plan on tackling this issue
My approach to resolve this issue :

Instead of showing the id number in the modal, I will modify the modal’s UI to display an appropriate image. This involves fetching and rendering the image in place of the ID, ensuring proper alignment and styling.

I will inspect the responsiveness issues in the edit agreement headers and update the css styles or use media queries to ensure that the headers are correctly displayed on different screen sizes, particularly on mobile devices.
Connect Validate/Sign Agreement Button:

I will connect the validate/sign agreement buttons on the edit agreement page to their respective modals. This will involve wiring up the button click events to trigger the appropriate modals, ensuring smooth user interaction.
Testing:

I will test the changes for mobile responsiveness, ensuring that the image displays correctly in the modal, and that the validate/sign buttons function properly across different devices and browsers.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by Ayoazeez26** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a software developer with 6 years experience building applications

### How I plan on tackling this issue
Fix the sign agreement modal to display an image instead of ID number
Check what's wrong with the edig agreement headers on mobile view and fix the responsiveness
Connect the validate/sign agreement button to the validate/sign agreement modals on the edit agreement page
ETA - 2 days

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, and Rust. With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
To improve the Agreement UI, I will address several important fixes that enhance functionality and user experience.

First, I will modify the "Sign Agreement" modal to display an image instead of the ID number. This change will provide users with a clearer visual reference, making it easier to identify the agreement they are signing.

Next, I will ensure that the edit agreement headers are fully responsive on mobile devices. This will involve adjusting styles and layouts to guarantee that all text and elements are easily readable and accessible, regardless of screen size.

Finally, on the edit agreement page, I will connect the "Validate" and "Sign Agreement" buttons to their respective modals. This integration will streamline the user flow, allowing users to access validation and signing options seamlessly, enhancing the overall efficiency of the agreement process.

These adjustments will contribute to a more intuitive and user-friendly Agreement UI, ensuring that users can navigate and interact with the platform effortlessly.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:                                                               
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/



### How I plan on tackling this issue
To elevate our application’s user experience and functionality, I am excited to propose the following impactful updates:

Sign Agreement Modal: I will enhance the sign agreement modal by replacing the ID number with an image. This visually engaging change will provide users with immediate context about the agreement, making the signing process not only clearer but also more engaging.

Mobile Responsiveness: I will ensure that the edit agreement headers are fully optimized for mobile devices. By meticulously refining the layout and styling, I will create a visually appealing and user-friendly interface that maintains readability and functionality across all screen sizes. This commitment to mobile responsiveness will significantly enhance user satisfaction and accessibility.

Edit Agreement Page Improvements: I will seamlessly connect the validate/sign agreement button to the relevant modals on the edit agreement page. This streamlined approach will empower users to validate or sign agreements with a single click, enhancing their workflow and minimizing any potential hurdles in the process.

I welcome feedback on these proposed enhancements and am eager to make any necessary adjustments to ensure they align with our goals and user expectations. My dedication to continuous improvement means I will rigorously test all updates to ensure they not only meet functional requirements but also provide a superior user experience.      

@Khauthymo I hope you give me the opportunity to contribute to this amazing project; I would be very grateful.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue
here are three quick fixes I need to make: 

  

**Display:** 

  

1. I’ll swap out the ID number for the actual image in the agreement modal. 

2. I’ll hook up the modals to the validate/sign buttons on the edit page. 

  

**Mobile:** 

  

1. I’ll fix the header layout breaking on small screens. 

2. I’ll clean up the spacing and alignment issues.

**Comment by melnikga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, my name is Georgiy, I'm a frontend developer. I have extensive experience in developing tools for Starknet, and I've participated in almost all ODHacks, during which I worked on many projects. My OnlyDust profile: https://app.onlydust.com/u/melnikga

### How I plan on tackling this issue
 I would modify the modal to show an image instead of just displaying the ID number, fix the responsive layout issues with agreement headers on mobile devices, and properly connect the validate/sign buttons to their respective modals. For the implementation, I would use shadcn modal components and make sure everything works smoothly across all screen sizes.

**Comment by ridwanalaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a frontend developer with 2 years experience building applications

### How I plan on tackling this issue
Fix the sign agreement modal to display an image instead of  ID number
Fix mobile responsiveness on edit agreement headers
Connect validate/sign agreement button to validate/sign agreement modals on edit agreement page
ETA - 72 hrs

**Comment by od-hunter** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi, please can I be assigned this please? This would be my first time contributing to this project and I would love to be the given the opportunity to contribute. I have experience in html, css, JavaScript,TypeScript and solidity, and Cairo.

### How I plan on tackling this issue
To solve this issue:
1.⁠ ⁠I’ll modify the sign agreement modal to display an image instead of the ID number by passing the image URL to the modal component.
2.⁠ ⁠I’ll enhance mobile responsiveness of edit agreement headers using css media queries and flexible layouts (Flexbox/Grid).
3.⁠ ⁠I’ll connect validate/sign agreement buttons to their respective modal functionalities by managing their open/close state and ensuring the modals display the correct content.

Please assign me, I’m ready to work. Thank you.

**Comment by Dprof-in-tech** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello, I'm Dprof-in-tech, a seasoned Full Stack Blockchain Developer, and I'm excited to be part of ODHACK 9! I have a strong foundation in technologies such as Next.js, TypeScript, JavaScript, React, Node.js, Rust, and Cairo, I've built extensive experience across the blockchain development landscape.

I first got involved with OnlyDust during Edition 2, and since then, I've made 39 contributions across 11 different projects. Working on the platform has really helped me sharpen my skills, especially when it comes to delivering great solutions under tight deadlines. I love combining technical know-how with a user-focused approach, whether it's building immersive 3D experiences or crafting smart contracts that solve real-world problems.

Throughout, I've consistently demonstrated the ability to adapt and contribute effectively to diverse challenges. I'm confident in my ability to tackle new problems and drive innovation within the blockchain space. As we kick off ODHACK 9, I'm eager to apply my previous experience and technical expertise to push the boundaries of what's possible.

You can view my public profile on OnlyDust here: https://app.onlydust.com/u/Dprof-in-tech


### How I plan on tackling this issue
Here's my approach to the Agreement UI fixes:

I'll tackle these issues in order of impact and complexity:

1. Agreement Modal Image Display:
   - I'll replace the ID number with an image display component
   - Plan to add proper image loading states and error handling
   - Will ensure the image scales appropriately within the modal
   - Add fallback display if image fails to load

2. Edit Agreement Page Modal Integration:
   - Need to wire up the validate/sign agreement buttons to their respective modals
   - I'll ensure proper state management between the button actions and modal triggers
   - Add loading states during validation process
   - Implement proper error handling and success feedback

3. Mobile Responsiveness:
   - Fix header layout issues on smaller screens
   - Implement proper breakpoints for different screen sizes
   - Use flexbox/grid for better header element alignment
   - Test across various mobile devices to ensure consistency

Implementation Plan:
- Day 1: Image display implementation and testing
- Day 2: Modal integration and validation flow
- Day 1-2: Mobile responsive fixes alongside other tasks

Testing Approach:
- Cross-browser testing (Chrome, Safari, Firefox)
- Mobile device testing (iOS/Android)
- UI/UX flow validation
- Responsive design verification

Expected completion time: 2-3 days

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a web2 and web3 developer and want to contribute to open source projects.

### How I plan on tackling this issue
I would modify the sign agreement modal to show an image instead of the ID number, fix mobile responsiveness issues with the edit agreement headers, and hook the validate/sign agreement button to their corresponding modals for smooth functionality.

**Comment by Psalmuel01** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a strong background in frontend engineering, UI/UX design, and Web3 development. Over the years, I’ve honed my skills in JavaScript frameworks like React and Next.js, as well as blockchain technologies. This gives me a unique edge in solving both technical and user experience problems.

### How I plan on tackling this issue
For the issue of displaying an image instead of an ID number on the agreement modal, I’ll modify the component to dynamically load and display the image associated with the agreement. I’ll ensure the image loads smoothly and implement fallback options in case the image isn’t available.

For mobile responsiveness on the edit agreement headers, I’ll leverage CSS techniques like Flexbox and Grid, combined with media queries, to ensure that the layout adjusts perfectly across different devices. This way, it’ll look and function well, no matter the screen size.

As for connecting the validate/sign agreement button to the modals, I’ll ensure the button triggers the right modal using React’s state management. I’ll also ensure validation happens before the modal opens, to avoid any errors in the process.

This approach will ensure everything works smoothly and is easy for users to navigate.

**Comment by Psalmuel01** [comment]
Done, please review
