### ISSUE TITLE
General Dapp Fixes

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/Custos-Dapp#24]
- [ ] Make search input on the nav bar work as should be
- [ ] Side bar,Nav bar, connect wallet fixes to align with figma design here
https://www.figma.com/design/3nZ7dFPCVz4fdnfP5ZGlL6/Custos-Diretriz?node-id=0-1&node-type=canvas&t=MFsQFI1P8Haph2Wl-0

**Comment by Joshaw-k** [comment]
Hello @Khauthymo I'm a frontend developer and would like to work on this issue :)

**Comment by Otaiki1** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hi , I am frontend developer with years of experience, would love to work on this issue as this is a project i am super interested in 

### How I plan on tackling this issue
Intend on following the design file dilligiently and replicating and making all components functional

**Comment by PoulavBhowmick03** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a Starknet Wolf. I am a software engineer at Invisible Studios, and a blockchain engineer with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem.

### How I plan on tackling this issue
I will implement comprehensive UI/UX improvements to align the application with the Figma design specifications. For the search functionality, I'll implement proper search logic in the navigation bar, including real-time filtering and search result display. The sidebar and navbar will be carefully refactored to match the Figma design system, ensuring proper spacing, typography, and component hierarchy. The connect wallet interface will be updated to match the design specifications, including proper button states, hover effects, and modal interactions. I'll ensure all components are responsive and maintain visual consistency across different screen sizes. Implementation will follow the exact color schemes, spacing, and interaction patterns from the Figma design. Expected completion time is 2-3 days, covering implementation, testing, and final design QA.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I will create a well documented and written codebase that will capture every bit of detail of the figma design and bring it to live, with the animations, mobile responsiveness, dark and light mode features as well as componentization for reusability across other pages, ican very much handle this task!

**Comment by SudiptaPaul-31** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
Hello! I’m Sudipta Paul, and I currently have 1.5 years of experience in the field of blockchain and web development. I'm eager to contribute to the improvements for the Dapp as outlined in this issue.

### How I plan on tackling this issue
My approach to overcome this issue:

I will start by closely examining the Figma design to understand the intended layout and functionality of the nav bar, sidebar, and wallet connection elements.
I will implement the search functionality in the nav bar, ensuring it responds correctly to user inputs. This will involve adding event listeners and integrating it with the existing search logic or API if applicable.Based on the Figma design, I will align the styles of the sidebar, nav bar, and connect wallet components. This may include modifying cssproperties or using a css framework for consistency with the design.

Once the changes are verified i will document the modifications made and create a pull request to submit my work, detailing the fixes and improvements.

**Comment by martinvibes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
hello @ i'm an experienced frontend developer and a blockchain developer  i would love to work on this issue 
Pleasee kindly assign :)

**Comment by stephanniegb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I’m a frontend engineer with  experience in building responsive, interactive UIs. I’ve worked on implementing pixel-perfect designs, and optimizing performance across various projects. My frontend technologies like css and tailwind will ensure that every detail matches Figma and works flawlessly.

### How I plan on tackling this issue
My approach:
- I’ll inspect the Figma design for the search input and navbar
- I will style the components  to match Figma’s design and ensure responsiveness.
- will implement their functionalities and make sure they behave as expected

**Comment by Yunusabdul38** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a strong background in software development, with a focus on blockchain technologies and smart contract development. My experience spans across various domains including decentralized applications (dApps), smart contract testing, and blockchain infrastructure.

With proficiency in Cairo (language), I am adept at writing and testing contracts on different blockchain platforms. I have hands-on experience with the StarkNet ecosystem and the Cairo programming language, which allows me to efficiently develop and test complex smart contracts.

Additionally, my experience with automated testing frameworks, version control systems, and continuous integration (CI) pipelines equips me to approach contract testing in a robust and scalable manner. My background in full-stack development, specifically with React and TypeScript, further strengthens my ability to contribute effectively to the frontend of decentralized applications, ensuring seamless integration with smart contracts.

Leveraging this experience, I can thoroughly implement and optimize the Cairo tests for the crime recorder and agreement contracts, ensuring high reliability and security.

### How I plan on tackling this issue
To align with the provided Figma design, I would start by modifying the hamburger menu to cover the entire screen when activated. This would involve creating a full-screen overlay, listing all the necessary navigation options (such as "Launch dApp" and "Company") directly within the expanded menu instead of using separate modals. This approach would provide a cleaner and more intuitive user experience.

For the landing page, I would adjust the text alignment and spacing to precisely match the Figma layout. This includes ensuring proper padding, margins, and typography settings that align with the design’s specifications. The goal is to create a consistent and visually appealing landing page that mirrors the design mockups closely.

Lastly, I would fix the spacing between the logo and hamburger icon, making sure it reflects the design in the provided image. Proper alignment and spacing will enhance the overall navigation experience and maintain design consistency across devices.

**Comment by KevinLatino** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I have a deep passion for Web3 and I am currently working as a frontend developer intern at a Web2 company, focusing on Next.js. Additionally, I am an active member of Dojo Coding, a prominent Web3 community in LATAM, which has given me great exposure to decentralized technologies.

Recently, I have been working on a project for Base LATAM's Buildathon, where I am gaining hands-on experience in building decentralized applications. I am eager to continue growing and contributing, and see this as a fantastic opportunity to further develop my skills and make a significant impact.

This is my first OD Hack, so I will appreciate it if you give me the chance to contribute to this amazing project.

Some frontend projects that i have:                                                               
https://buildmyevent.xyz/
https://peritazgo-website.vercel.app/



### How I plan on tackling this issue
1. **Make Search Input Work**: Implement functionality to ensure the search input in the nav bar processes user input correctly and triggers the appropriate search action.

2. **Align Sidebar and Nav Bar with Figma Design**: Review and adjust styles, spacing, and positioning of the sidebar and nav bar elements to ensure they match the provided Figma design.

3. **Connect Wallet Fixes**: Make adjustments to the connect wallet feature, ensuring it works seamlessly and adheres to the design specifications from Figma. This may involve updating styles, button placements, or functionality to ensure a smooth user experience.
                                                                                                                                                   @Khauthymo I hope you give me the opportunity to contribute to this amazing project; I would be very grateful.
