### ISSUE TITLE
Refactor Custos to a PWA

### ISSUE THREAD

**Issue by Khauthymo** [Custos-Diretriz/Custos-Dapp#25]
Custos PWA Refactor

We're refactoring Custos into a Progressive Web App (PWA) to improve performance, accessibility, and user experience. This will enable offline functionality, faster load times, and a native app-like feel across platforms, all while using a single codebase.

**Comment by MayowaObisesan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'll like to work on this issue.I am a web3 frontend developer with full-stack development experience.
I have worked on various frontend projects building exciting and captivating UI for good User Experience. I believe in pixel-perfect design and UI implementations.
I have a knack for building amazing web and mobile UI.

### How I plan on tackling this issue
Once I have understood the problem, I will fork the repo, and simulate the issue that was described. Depending on the complexity of the issue. If it is a frontend issue with an easy tag, I can raise a PR in minutes, but for more complex UI, I raise the PR the same day.

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I am a fullstack developer worked with various frontend frameworks over the years as well as different backend languages. currently transitioning into the web3 space.

### How I plan on tackling this issue
I can easily convert the current Custos build to a PWA to perform with more speed, efficiency and also to be more accessible

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/custos-diretriz).

### My background and how it can be leveraged
I'm a Full Stack Blockchain Developer with demonstrable expertise across modern web and blockchain technologies. My tech stack centers on Next.js, TypeScript, React, and Node.js for web development, complemented by Three.js for 3D experiences, and Solidity/Rust for blockchain solutions. 

What sets me apart is my proven track record on OnlyDust, where I've made 83 significant contributions across 15 different projects since Edition 1. This extensive involvement reflects my ability to deliver quality solutions under tight deadlines while adapting to diverse project requirements.  

With my deep experience in hackathon environments, I bring both technical excellence and practical development skills to the table. I'm confident I can contribute meaningfully to pushing the boundaries of what's possible in blockchain development while maintaining a focus on user-centric solutions. 

  

My profile (https://app.onlydust.com/u/Ugo-X) showcases my consistent ability to deliver results across various blockchain challenges. I'm excited to bring this experience and drive for innovation to your team. 

### How I plan on tackling this issue


1. **Service Worker Setup:** I'll set up a service worker to handle offline functionality, cache static assets, and implement background synchronization.

2. **Initial Configuration:** I'll create a Web App Manifest to define app metadata and icons. I'll also optimize meta tags for iOS and Android compatibility and implement a caching strategy using Workbox.

3. **Core Improvements:** I'll implement app shell architecture for faster initial loads, dynamically cache API responses, use IndexedDB for offline data persistence, and optimize bundle size through code splitting and lazy loading.

4. **User Experience Enhancements:** I'll add an "Add to Home Screen" prompt, implement push notifications, handle offline/online state transitions gracefully, and use loading indicators and placeholder content to improve perceived performance.

**Estimated Timeline:** 2-3 days
